### ISSUE TITLE
Feature: User can view a list of movies

### ISSUE THREAD

**Issue by seankim248** [seankim248/binge-list#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of their movies.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to scroll down a list of movies in a random order.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-01-03 at 10 46 11 AM](https://user-images.githubusercontent.com/59588689/147967609-a2e8be2b-f973-43e6-bf52-e41b2561bd75.png)

![Screen Shot 2022-01-03 at 10 00 29 AM](https://user-images.githubusercontent.com/59588689/147963721-ec619589-0bda-4c73-8295-95e2fbb1ea20.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML and CSS Layout without the card components
- [x] Make a XMLHttpRequest to api
- [x] Test to double check that receiving data is correct using console logs
- [x] Create movie card component
- [x] Append each movie card component to div with class "card-container"
- [x] Make the page look nice on both mobile and desktop versions
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
