### ISSUE TITLE
Feature: User can view a description of each movie

### ISSUE THREAD

**Issue by seankim248** [seankim248/binge-list#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a description of each movie.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click on "see description" text located at the bottom right part of the card and view the description.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-01-04 at 11 01 28 AM](https://user-images.githubusercontent.com/59588689/148110180-97bd632f-047b-4791-a766-237b824bc986.png)
![Screen Shot 2022-01-04 at 11 02 12 AM](https://user-images.githubusercontent.com/59588689/148110205-48172287-f249-4ac2-8283-44a926f4fcef.png)

![Screen Shot 2022-01-04 at 11 03 45 AM](https://user-images.githubusercontent.com/59588689/148110414-31fb6868-95be-45e8-936f-516ee13c6276.png)

![Screen Shot 2022-01-04 at 11 02 45 AM](https://user-images.githubusercontent.com/59588689/148110273-d599d3ce-8041-4da2-9010-c022f3d7b797.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create a p element with the text content of "See Description" at the bottom right corner of the card component.
- [x] add an eventListener for when the p element is clicked
   - [x] make the width twice as long
   - [x] create an overlay to cover the image
   - [x] add description of the movie
   - [x] change p element text content to "Close Description"
- [x] make transition smooth
- [x] make both mobile and desktop versions look nice when event fires
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
