### ISSUE TITLE
Feature: User can filter movies by genres

### ISSUE THREAD

**Issue by seankim248** [seankim248/binge-list#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can filter movies by genres.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click on several buttons that will direct them to a movie list page of the chosen genre.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-01-05 at 10 08 34 AM](https://user-images.githubusercontent.com/59588689/148267124-5ff8b262-373a-49ff-8cc7-096aaaf85d9e.png)

![Screen Shot 2022-01-05 at 10 08 46 AM](https://user-images.githubusercontent.com/59588689/148267151-19028f90-250f-4820-8d0b-2ab84d759129.png)
![Screen Shot 2022-01-05 at 10 08 59 AM](https://user-images.githubusercontent.com/59588689/148267184-f1350c7a-844a-40f4-b088-ecd457624e0b.png)
![Screen Shot 2022-01-05 at 10 09 12 AM](https://user-images.githubusercontent.com/59588689/148267203-51221004-70bf-495d-9c99-ec8ac5c33773.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create buttons for various genres of movies
- [x] add an eventListener for each button
   - [x] highlights the text
   - [x] viewswaps to page 1 of that genre
- [x] make it look nice on both mobile and desktop versions
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
