### ISSUE TITLE
Feature: User can search movies by name

### ISSUE THREAD

**Issue by seankim248** [seankim248/binge-list#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search movies by name.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to type the name of a desired movie in a search bar.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-01-05 at 2 41 14 PM](https://user-images.githubusercontent.com/59588689/148299925-a1ea9bdc-6916-43ef-a610-3596b6bc71ed.png)
![Screen Shot 2022-01-05 at 2 41 51 PM](https://user-images.githubusercontent.com/59588689/148299956-16980573-1cf9-4d67-abea-c799669a0145.png)

![Screen Shot 2022-01-05 at 2 42 11 PM](https://user-images.githubusercontent.com/59588689/148299992-51b481b8-56fc-4771-b597-d6100ae5bc0b.png)
![Screen Shot 2022-01-05 at 2 42 25 PM](https://user-images.githubusercontent.com/59588689/148300022-883777bd-a676-40f7-89ca-1b850e0bebc4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add a search bar component on the top left corner
- [x] add an eventListener to the text input that will show a list of movies if the name matches the search description when pressing enter
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
