### ISSUE TITLE
Feature: User can add a movie to a watchlist

### ISSUE THREAD

**Issue by seankim248** [seankim248/binge-list#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a movie to a watchlist.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Upon pressing the plus button, a green checkmark will show indicating that the movie has been added to the watchlist.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-01-05 at 4 39 19 PM](https://user-images.githubusercontent.com/59588689/148309769-2d60423c-a7ec-4712-895a-056bc35d78a4.png)

![Screen Shot 2022-01-05 at 4 40 09 PM](https://user-images.githubusercontent.com/59588689/148309795-bcb28bf6-d7a9-424e-b6d8-c3369b884735.png)
![Screen Shot 2022-01-05 at 4 40 29 PM](https://user-images.githubusercontent.com/59588689/148309824-0bbd9fb5-4d3b-4c10-8148-56fc103ae608.png)

![Screen Shot 2022-01-05 at 4 40 44 PM](https://user-images.githubusercontent.com/59588689/148309854-5f5a52dc-8f98-4401-9a6b-1457f6abb61c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add a plus icon underneath the rating
- [x] add an eventListener for the plus icon
   - [x] changes icon to a green checkmark
   - [x] adds the movie response object into an array in localStorage
- [x] add an eventListener for the checkmark icon
   - [x] changes icon to a plus icon
   - [x] removes the movie response object from the array in localStorage
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
