### ISSUE TITLE
Feature: User can view their watchlist

### ISSUE THREAD

**Issue by seankim248** [seankim248/binge-list#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their watchlist.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to press a watchlist tab which will direct them to a watchlist page that shows all the added movies.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-01-06 at 4 27 29 PM](https://user-images.githubusercontent.com/59588689/148471435-38d07428-bde7-40a0-b79f-458014fa43f9.png)
![Screen Shot 2022-01-06 at 4 27 41 PM](https://user-images.githubusercontent.com/59588689/148471451-c14b5f34-3267-4c5f-8e41-36cf0b427e62.png)
![Screen Shot 2022-01-06 at 4 27 54 PM](https://user-images.githubusercontent.com/59588689/148471470-46c970bc-968f-40b5-ac67-34a342da5635.png)
![Screen Shot 2022-01-06 at 4 28 05 PM](https://user-images.githubusercontent.com/59588689/148471482-9504e72a-af52-46b9-86de-454b56704673.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create a watchlist tab in the header
- [x] create the watchlist view
   - [x] h1 element
   - [x] p element
- [x] add an eventListener for the watchlist so that it view-swaps to a the watchlist view
- [x] add an eventListener for the Logo so that it goes back to the popular page
- [x] append all movies from the movies array in localStorage
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
