### ISSUE TITLE
Feature: User can remove movie from their watchlist

### ISSUE THREAD

**Issue by seankim248** [seankim248/binge-list#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove movie from their watchlist.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User has the option to uncheck the green checkmark to remove movie from watchlist.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-01-10 at 10 06 33 AM](https://user-images.githubusercontent.com/59588689/148816480-96e832b5-facd-4289-9901-f9aa54579bee.png)
![Screen Shot 2022-01-10 at 10 07 27 AM](https://user-images.githubusercontent.com/59588689/148816546-7a0f2f91-d09c-4950-8691-4d351647e767.png)
![Screen Shot 2022-01-10 at 10 07 43 AM](https://user-images.githubusercontent.com/59588689/148816587-4884e180-d7c6-4666-92f9-59bf1d5689af.png)
![Screen Shot 2022-01-10 at 10 07 55 AM](https://user-images.githubusercontent.com/59588689/148816622-4636ba0a-adcf-4007-a6af-238f376a523c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] unchecking the check icon removes respective movie from the movies array
- [ ] unchecking the check icon in the watchlist view will uncheck it as well in the home view
- [ ] unchecking the check icon in the home view should remove the movie from the watchlist

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
