### ISSUE TITLE
Feature: User can see multiple pages of results

### ISSUE THREAD

**Issue by seankim248** [seankim248/binge-list#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see multiple pages of results.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user reaches at the bottom of the list they will be able to press on buttons that contain numbers based on the page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-01-03 at 5 48 11 PM](https://user-images.githubusercontent.com/59588689/147999008-b5cd701e-cd53-4545-99aa-6723553730f4.png)
![Screen Shot 2022-01-03 at 5 48 27 PM](https://user-images.githubusercontent.com/59588689/147999020-d26d11fa-efb2-4366-99d2-49eae1fd47eb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] add buttons numbered 1-4 at the bottom of the page.
- [ ] view-swap to second page when button number 2 is clicked on.
- [ ] Make sure to view-swap with the rest of the buttons.
- [ ] When the button is clicked, the number should be highlighted indicating the current page.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
